import type { Metadata } from "next";
import { Provider as ChakraProvider } from "@/lib/chakra-ui/provider";
import { Provider as QueryClientProvider } from "@/lib/react-query/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ChakraProvider>
          <QueryClientProvider>{children}</QueryClientProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
